import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { CTAButton } from "@/components/CTAButton";
import { HeroArtwork } from "@/components/HeroArtwork";

export default function About(){return <main><Nav/>
<section className="innerHero hasHeroArtwork"><div className="blob blobThree"/><p className="eyebrow">ABOUT BLUEPRINT BUDDIES</p><h1>PROPERTY<br/>DEMAND,<br/><span>STRUCTURED.</span></h1><p className="innerLead">We are building a multi-market property-demand network across Pakistan, the USA and the UK: one place where buyers, sellers, investors and renters can express what they actually need, and participating realtors can work opportunities that fit their market.</p><HeroArtwork src="/images/heroes/about.webp" alt="People, architecture and communities connected through property decisions" priority/></section>
<section className="manifesto"><p className="eyebrow">THE IDEA</p><h2>THE INTERNET HAS ENOUGH PROPERTY POSTS.<br/><span>THE PROBLEM IS MATCHING INTENT.</span></h2><div className="manifestoCopy"><p>Traditional property discovery often begins with listings and scattered conversations. BLUEPRINT BUDDIES starts from the other side: the customer&apos;s requirement.</p><p>We capture location, budget, property type and timeframe in a consistent structure, then use those signals to make realtor matching more relevant.</p></div></section>
<section className="principles"><article><span>01</span><h3>LOCAL FIRST</h3><p>Property expertise is territorial. Matching begins with the actual market.</p></article><article><span>02</span><h3>INTENT OVER NOISE</h3><p>A structured requirement is more useful than an unqualified inquiry.</p></article><article><span>03</span><h3>PRIVACY BY DEFAULT</h3><p>Consumer contact information is not displayed publicly.</p></article><article><span>04</span><h3>OUTCOMES MATTER</h3><p>The long-term system learns from claims, follow-ups and transaction outcomes.</p></article></section>
<section className="finalCta shortCta"><p className="eyebrow">MAKE YOUR NEXT MOVE</p><h2>START WITH<br/><span>THE REQUIREMENT.</span></h2><CTAButton href="/get-started">SUBMIT REQUIREMENT</CTAButton></section><Footer/></main>}
