"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Flame } from "lucide-react";
import { CITY_AREAS, PROPERTY_TYPES, TIMEFRAMES } from "@/lib/market";
import type { LeadType } from "@/lib/types";

const TYPES: {id:LeadType; label:string; kicker:string}[]=[
  {id:"buy",label:"BUY",kicker:"Find your next property"},{id:"sell",label:"SELL",kicker:"Reach serious buyers"},{id:"invest",label:"INVEST",kicker:"Find matching opportunities"},{id:"rent",label:"RENT",kicker:"Find your next place"},
];
const inputClass="field";
export function LeadWizard(){
 const [step,setStep]=useState(0); const [busy,setBusy]=useState(false); const [done,setDone]=useState<{id:string;temperature:string}|null>(null); const [error,setError]=useState("");
 const [data,setData]=useState<any>({type:"buy",city:"Karachi",area:"DHA",propertyType:"House",timeframe:"Within 30 days",paymentMode:"Cash",name:"",phone:"",email:"",ownerConfirmed:false});
 const areas=useMemo(()=>CITY_AREAS[data.city]||["Other"],[data.city]);
 useEffect(()=>{const q=new URLSearchParams(window.location.search);const city=q.get("city");const type=q.get("type") as LeadType|null;if(city && CITY_AREAS[city]) setData((d:any)=>({...d,city,area:CITY_AREAS[city][0]}));if(type && TYPES.some(t=>t.id===type)) setData((d:any)=>({...d,type}));},[]);
 function patch(k:string,v:any){setData((d:any)=>({...d,[k]:v}));}
 async function submit(){setBusy(true);setError("");try{const payload={...data,budgetMin:data.budgetMin?Number(data.budgetMin):undefined,budgetMax:data.budgetMax?Number(data.budgetMax):undefined,expectedPrice:data.expectedPrice?Number(data.expectedPrice):undefined,source:new URLSearchParams(location.search).get("source")||"website",utmSource:new URLSearchParams(location.search).get("utm_source")||undefined,utmMedium:new URLSearchParams(location.search).get("utm_medium")||undefined,utmCampaign:new URLSearchParams(location.search).get("utm_campaign")||undefined};const r=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Submission failed");setDone({id:j.leadId,temperature:j.temperature});}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(done)return <div className="successPanel"><div className="successIcon"><Check/></div><p className="eyebrow">REQUIREMENT RECEIVED</p><h2>WE'LL MATCH THE RIGHT PROPERTY PEOPLE.</h2><p>Your reference is <strong>{done.id}</strong>. Your requirement is currently marked <strong>{done.temperature.replace("_"," ").toUpperCase()}</strong> and will be reviewed before being shown as verified.</p><a className="ctaButton inlineButton" href="/"><span className="ctaFill"/><span className="ctaText">BACK HOME <ArrowRight size={18}/></span></a></div>;
 return <div className="wizard">
  <div className="wizardTop"><span>0{step+1} / 04</span><div className="progress"><i style={{width:`${(step+1)*25}%`}}/></div></div>
  {step===0&&<section className="wizardStage"><p className="eyebrow">YOUR MOVE</p><h1>WHAT ARE YOU HERE TO DO?</h1><div className="typeGrid">{TYPES.map(t=><button key={t.id} className={`typeChoice ${data.type===t.id?"active":""}`} onClick={()=>patch("type",t.id)}><span>{t.label}</span><small>{t.kicker}</small></button>)}</div></section>}
  {step===1&&<section className="wizardStage"><p className="eyebrow">LOCATION</p><h1>WHERE IS THE PROPERTY?</h1><div className="formGrid"><label>CITY<select className={inputClass} value={data.city} onChange={e=>{patch("city",e.target.value);patch("area",CITY_AREAS[e.target.value]?.[0]||"Other")}}>{Object.keys(CITY_AREAS).map(c=><option key={c}>{c}</option>)}</select></label><label>AREA / SOCIETY<select className={inputClass} value={data.area} onChange={e=>patch("area",e.target.value)}>{areas.map(a=><option key={a}>{a}</option>)}</select></label><label>PROPERTY TYPE<select className={inputClass} value={data.propertyType} onChange={e=>patch("propertyType",e.target.value)}>{PROPERTY_TYPES.map(p=><option key={p}>{p}</option>)}</select></label><label>SIZE<input className={inputClass} placeholder="e.g. 500 sq yd" value={data.size||""} onChange={e=>patch("size",e.target.value)}/></label></div></section>}
  {step===2&&<section className="wizardStage"><p className="eyebrow">INTENT</p><h1>MAKE THE REQUIREMENT USEFUL.</h1><div className="formGrid"><label>{data.type==="sell"?"EXPECTED PRICE (PKR)":"MIN BUDGET (PKR)"}<input className={inputClass} type="number" value={data.type==="sell"?(data.expectedPrice||""):(data.budgetMin||"")} onChange={e=>patch(data.type==="sell"?"expectedPrice":"budgetMin",e.target.value)}/></label>{data.type!=="sell"&&<label>MAX BUDGET (PKR)<input className={inputClass} type="number" value={data.budgetMax||""} onChange={e=>patch("budgetMax",e.target.value)}/></label>}<label>TIMEFRAME<select className={inputClass} value={data.timeframe} onChange={e=>patch("timeframe",e.target.value)}>{TIMEFRAMES.map(t=><option key={t}>{t}</option>)}</select></label><label>PAYMENT<select className={inputClass} value={data.paymentMode||""} onChange={e=>patch("paymentMode",e.target.value)}><option>Cash</option><option>Installments</option><option>Financing / Mortgage</option><option>Open to options</option></select></label>{["buy","rent"].includes(data.type)&&<label>BEDROOMS<select className={inputClass} value={data.bedrooms||"Open"} onChange={e=>patch("bedrooms",e.target.value)}><option>Open</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5+</option></select></label>}{data.type!=="sell"&&<label>PURPOSE<input className={inputClass} placeholder={data.type==="invest"?"e.g. long-term investment":"e.g. family residence"} value={data.purpose||""} onChange={e=>patch("purpose",e.target.value)}/></label>}{data.type==="sell"&&<label className="checkLine"><input type="checkbox" checked={!!data.ownerConfirmed} onChange={e=>patch("ownerConfirmed",e.target.checked)}/><span>I am the owner / authorized seller</span></label>}{data.type==="invest"&&<label>INVESTMENT GOAL<select className={inputClass} value={data.investmentGoal||"Appreciation"} onChange={e=>patch("investmentGoal",e.target.value)}><option>Appreciation</option><option>Rental income</option><option>Both</option></select></label>}</div></section>}
  {step===3&&<section className="wizardStage"><p className="eyebrow"><Flame size={15}/> FINAL STEP</p><h1>WHERE SHOULD REALTORS REACH YOU?</h1><div className="formGrid"><label>FULL NAME<input required className={inputClass} value={data.name} onChange={e=>patch("name",e.target.value)} placeholder="Your name"/></label><label>WHATSAPP / PHONE<input required className={inputClass} value={data.phone} onChange={e=>patch("phone",e.target.value)} placeholder="03XX XXXXXXX"/></label><label>EMAIL <small>OPTIONAL</small><input className={inputClass} type="email" value={data.email} onChange={e=>patch("email",e.target.value)} placeholder="you@email.com"/></label></div><p className="privacyNote">Your contact details stay hidden from the public marketplace and are released only to authorized realtors who claim your opportunity.</p>{error&&<p className="errorText">{error}</p>}</section>}
  <div className="wizardActions">{step>0?<button className="backBtn" onClick={()=>setStep(s=>s-1)}><ArrowLeft/> BACK</button>:<span/>}{step<3?<button className="nextBtn" onClick={()=>setStep(s=>s+1)}>CONTINUE <ArrowRight/></button>:<button disabled={busy||!data.name||data.phone.length<10} className="nextBtn" onClick={submit}>{busy?"SUBMITTING…":"SUBMIT REQUIREMENT"}<ArrowRight/></button>}</div>
 </div>
}
