"use client";

import { useEffect, useState } from "react";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { firebaseAuth } from "@/lib/firebase-client";
import { ArrowLeft, Check, CircleDollarSign, LogOut, RefreshCw, ShieldCheck, Sparkles, X } from "lucide-react";
import { effectiveLeadPrice, formatPlanPrice } from "@/lib/pricing";
import type { PricingPlan } from "@/lib/pricing";
import { getMarket } from "@/lib/market";

export function RealtorBilling(){
  const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[notice,setNotice]=useState("");
  async function token(){const u=firebaseAuth.currentUser;if(!u)throw new Error("NO_USER");return u.getIdToken(true)}
  async function load(){setLoading(true);try{const t=await token();const r=await fetch("/api/realtor/billing",{headers:{authorization:`Bearer ${t}`},cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}catch(e:any){setNotice(e.message||"Could not load billing.")}finally{setLoading(false)}}
  useEffect(()=>onAuthStateChanged(firebaseAuth,u=>u?load():location.href="/login"),[]);
  async function activate(id:string){setBusy(id);setNotice("");try{const t=await token();const r=await fetch("/api/realtor/billing",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({packageId:id})});const j=await r.json();if(!r.ok)throw new Error(j.error);setNotice(j.package.kind==="subscription"?`${j.package.name} test plan activated with ${j.package.leadCap} verified leads. No money was charged.`:`1 test individual lead added. No money was charged.`);await load()}catch(e:any){setNotice(e.message||"Could not activate package.")}finally{setBusy("")}}
  const market=data?getMarket(data.country):null;
  const account=data?.account||{};
  const subscriptionRemaining=Number(account.subscriptionLeadsRemaining||0);
  const paygRemaining=Number(account.paygLeadBalance||0);
  const legacyRemaining=Number(account.legacyCreditsBalance||0);
  const totalRemaining=Number(account.totalLeadsRemaining||0);
  return <div className="portalShell"><header className="portalTopbar"><a className="portalBrand" href="/">BLUEPRINT <span>BUDDIES</span></a><div><a className="portalBackLink" href="/realtor/dashboard"><ArrowLeft size={15}/> DASHBOARD</a><button onClick={()=>signOut(firebaseAuth).then(()=>location.href="/")}><LogOut size={16}/> LOG OUT</button></div></header><main className="billingShell"><header className="billingHero"><div><p className="eyebrow">VERIFIED LEADS / PRICING</p><h1>LEADS<br/><span>& ACCESS.</span></h1><p>{market?`${market.name} realtor pricing and verified-lead allowance.`:"Manage your realtor access."} Only verified leads consume an allowance.</p></div><button className="outlineAction" onClick={load}><RefreshCw size={16}/> REFRESH</button></header>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="Dismiss"><X size={16}/></button></div>}{loading?<div className="portalLoading"><span/><p>Loading pricing…</p></div>:data&&<><section className="billingAccount billingAccountFive"><article><span>CURRENT PLAN</span><strong>{String(account.planId||"none").replace("pk-","").toUpperCase()}</strong></article><article><span>PLAN STATUS</span><strong>{String(account.subscriptionStatus||"none").replaceAll("_"," ").toUpperCase()}</strong></article><article className="creditBalance"><CircleDollarSign/><span>VERIFIED LEADS LEFT</span><strong>{totalRemaining}</strong></article><article><span>MONTHLY USED</span><strong>{Number(account.planLeadsUsed||0)} / {Number(account.planLeadCap||0)}</strong></article><article><span>INDIVIDUAL LEADS</span><strong>{paygRemaining}</strong></article></section>
      {data.testPurchases?<section className="testBillingNotice"><ShieldCheck/><div><strong>TEST ACTIVATION MODE.</strong><p>The real Pakistan prices are shown below, but these buttons only simulate activation while checkout is being connected. No money is charged.</p></div></section>:<section className="testBillingNotice livePricingNotice"><ShieldCheck/><div><strong>PRICING IS CONFIGURED.</strong><p>Choose the plan that fits your lead volume. Online payment activation will be enabled when the production payment gateway is connected.</p></div></section>}
      <section><div className="sectionLine"><div><p className="eyebrow">{market?.shortName||"MARKET"} ACCESS</p><h2>{data.pricingAvailable?"CHOOSE A PLAN":"COMING SOON"}</h2></div><span>{data.packages?.length||0} OPTIONS</span></div>{data.pricingAvailable?<div className="packageGrid pricingBillingGrid">{(data.packages||[]).map((p:PricingPlan)=><article key={p.id} className={p.featured?"featured":""}>{p.featured&&<span className="packageMode"><Sparkles size={12}/> BEST VALUE</span>}<span className="billingPlanKind">{p.kind==="subscription"?"MONTHLY SUBSCRIPTION":"PAY AS YOU GO"}</span><h3>{p.name}</h3><div className="billingPlanPrice"><strong>{formatPlanPrice(p)}</strong><small>{p.billingInterval==="month"?"/ MONTH":"/ LEAD"}</small></div><div className="billingLeadCap"><strong>{p.leadCap}</strong><span>{p.leadCap===1?"VERIFIED LEAD":"VERIFIED LEADS"}</span></div>{p.kind==="subscription"&&<p className="effectiveRate">≈ PKR {effectiveLeadPrice(p).toLocaleString("en-PK")} per verified lead at full usage</p>}<p>{p.description}</p><ul>{p.features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul>{data.testPurchases?<button disabled={busy===p.id} onClick={()=>activate(p.id)}>{busy===p.id?"ACTIVATING…":p.kind==="subscription"?`ACTIVATE ${p.name} TEST PLAN`:"ADD 1 TEST LEAD"}</button>:<a className="billingContactCta" href={`/contact?subject=${encodeURIComponent(p.name+" pricing")}`}>CONTACT TO ACTIVATE →</a>}</article>)}</div>:<div className="emptyBox"><strong>PRICING FOR THIS MARKET IS NOT LIVE YET.</strong><p>Pakistan pricing is configured. USA and UK package pricing will remain disabled until the final numbers are approved.</p><a className="secondaryLink" href="/contact">CONTACT SUPPORT →</a></div>}</section>
      {(subscriptionRemaining>0||paygRemaining>0||legacyRemaining>0)&&<p className="billingBalanceNote">Your next claim uses monthly subscription allowance first, then individual lead balance, then any remaining legacy beta credits.</p>}
    </>}</main></div>
}
