"use client";

import { useEffect, useState } from "react";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { firebaseAuth } from "@/lib/firebase-client";
import { ArrowLeft, Check, Coins, LogOut, RefreshCw, ShieldCheck, X } from "lucide-react";

export function RealtorBilling(){
  const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[notice,setNotice]=useState("");
  async function token(){const u=firebaseAuth.currentUser;if(!u)throw new Error("NO_USER");return u.getIdToken(true)}
  async function load(){setLoading(true);try{const t=await token();const r=await fetch("/api/realtor/billing",{headers:{authorization:`Bearer ${t}`},cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}catch(e:any){setNotice(e.message||"Could not load billing.")}finally{setLoading(false)}}
  useEffect(()=>onAuthStateChanged(firebaseAuth,u=>u?load():location.href="/login"),[]);
  async function activate(id:string){setBusy(id);setNotice("");try{const t=await token();const r=await fetch("/api/realtor/billing",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${t}`},body:JSON.stringify({packageId:id})});const j=await r.json();if(!r.ok)throw new Error(j.error);setNotice(`${j.package.name} activated — ${j.package.credits} test credits added.`);await load()}catch(e:any){setNotice(e.message||"Could not activate package.")}finally{setBusy("")}}
  return <div className="portalShell"><header className="portalTopbar"><a className="portalBrand" href="/">BLUEPRINT <span>BUDDIES</span></a><div><a className="portalBackLink" href="/realtor/dashboard"><ArrowLeft size={15}/> DASHBOARD</a><button onClick={()=>signOut(firebaseAuth).then(()=>location.href="/")}><LogOut size={16}/> LOG OUT</button></div></header><main className="billingShell"><header className="billingHero"><div><p className="eyebrow">BILLING / TEST MODE</p><h1>CREDITS<br/><span>& ACCESS.</span></h1><p>Use test credits to validate the full lead-claiming flow before a live payment gateway is connected.</p></div><button className="outlineAction" onClick={load}><RefreshCw size={16}/> REFRESH</button></header>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="Dismiss"><X size={16}/></button></div>}{loading?<div className="portalLoading"><span/><p>Loading billing…</p></div>:data&&<><section className="billingAccount"><article><span>CURRENT PLAN</span><strong>{String(data.account.planId||"beta").toUpperCase()}</strong></article><article><span>STATUS</span><strong>{String(data.account.subscriptionStatus||"pending").replaceAll("_"," ").toUpperCase()}</strong></article><article className="creditBalance"><Coins/><span>LEAD CREDITS</span><strong>{data.account.creditsBalance}</strong></article><article><span>MODE</span><strong>{String(data.mode||"").replaceAll("_"," ").toUpperCase()}</strong></article></section><section className="testBillingNotice"><ShieldCheck/><div><strong>NO REAL PAYMENT IS TAKEN HERE.</strong><p>This page is a billing simulator for beta testing. When you choose a live gateway, these package actions will be replaced by real checkout + payment verification.</p></div></section><section><div className="sectionLine"><div><p className="eyebrow">TEST PACKAGE CATALOG</p><h2>TOP UP</h2></div><span>{data.packages?.length||0} OPTIONS</span></div><div className="packageGrid">{(data.packages||[]).map((p:any)=><article key={p.id}><span className="packageMode">TEST</span><h3>{p.name}</h3><strong>{p.credits}<small> CREDITS</small></strong><p>{p.description}</p><ul><li><Check size={15}/> Adds credits instantly</li><li><Check size={15}/> Tests lead claiming</li><li><Check size={15}/> No card or money charged</li></ul><button disabled={!data.testPurchases||busy===p.id} onClick={()=>activate(p.id)}>{busy===p.id?"ACTIVATING…":"ACTIVATE TEST PACKAGE"}</button></article>)}</div>{!data.testPurchases&&<p className="billingDisabled">Test package activation is disabled by environment configuration.</p>}</section></>}</main></div>
}
