import { z } from "zod";
import { getAreas, getMarket, isCountryCode, PROPERTY_TYPES, TIMEFRAMES } from "./market";

const countrySchema=z.enum(["PK","US","UK"]).default("PK");

export const leadSchema=z.object({
  country:countrySchema,
  type:z.enum(["buy","sell","invest","rent"]),city:z.string().min(2).max(80),area:z.string().min(2).max(120),propertyType:z.string().min(2).max(80),
  budgetMin:z.number().nonnegative().optional(),budgetMax:z.number().nonnegative().optional(),size:z.string().max(80).optional(),bedrooms:z.string().max(30).optional(),paymentMode:z.string().max(60).optional(),purpose:z.string().max(100).optional(),timeframe:z.string().min(2).max(80),ownerConfirmed:z.boolean().optional(),expectedPrice:z.number().nonnegative().optional(),investmentGoal:z.string().max(100).optional(),name:z.string().min(2).max(100),phone:z.string().min(7).max(30).refine(v=>v.replace(/\D/g,"").length>=7,"Invalid phone number"),email:z.string().email().optional().or(z.literal("")),contactConsent:z.literal(true),source:z.string().max(80).optional(),campaign:z.string().max(120).optional(),contentId:z.string().max(120).optional(),utmSource:z.string().max(120).optional(),utmMedium:z.string().max(120).optional(),utmCampaign:z.string().max(120).optional()
}).superRefine((v,ctx)=>{const m=getMarket(v.country);if(!m.cities[v.city])ctx.addIssue({code:"custom",path:["city"],message:"Unsupported city for this country"});else if(!getAreas(v.country,v.city).includes(v.area))ctx.addIssue({code:"custom",path:["area"],message:"Unsupported area for this city"});if(!PROPERTY_TYPES.includes(v.propertyType))ctx.addIssue({code:"custom",path:["propertyType"],message:"Unsupported property type"});if(!TIMEFRAMES.includes(v.timeframe))ctx.addIssue({code:"custom",path:["timeframe"],message:"Unsupported timeframe"});if(v.budgetMin!==undefined&&v.budgetMax!==undefined&&v.budgetMin>v.budgetMax)ctx.addIssue({code:"custom",path:["budgetMax"],message:"Maximum budget must be greater than minimum budget"});if(v.type==="sell"&&v.ownerConfirmed!==true)ctx.addIssue({code:"custom",path:["ownerConfirmed"],message:"Seller authorization is required"});if(v.type==="sell"&&(!v.expectedPrice||v.expectedPrice<=0))ctx.addIssue({code:"custom",path:["expectedPrice"],message:"Expected price is required"});if(v.type!=="sell"&&!((v.budgetMin||0)>0||(v.budgetMax||0)>0))ctx.addIssue({code:"custom",path:["budgetMax"],message:"A budget is required"});});

const realtorFields={country:countrySchema,fullName:z.string().min(2).max(100),agencyName:z.string().min(2).max(140),phone:z.string().min(7).max(30),whatsapp:z.string().min(7).max(30),city:z.string().min(2).max(80),areas:z.array(z.string()).min(1),propertyTypes:z.array(z.string()).min(1),leadTypes:z.array(z.enum(["buy","sell","invest","rent"])).min(1),experience:z.string().max(80).optional(),website:z.string().url().optional().or(z.literal("")),instagram:z.string().max(200).optional(),facebook:z.string().max(200).optional(),about:z.string().max(800).optional(),logoDriveFileId:z.string().max(200).optional().or(z.literal(""))};
function validateRealtorMarket(v:{country:"PK"|"US"|"UK";city:string;areas:string[];propertyTypes:string[]},ctx:z.RefinementCtx){if(!isCountryCode(v.country)||!getMarket(v.country).cities[v.city])ctx.addIssue({code:"custom",path:["city"],message:"Unsupported city for this country"});const allowed=getAreas(v.country,v.city);if(v.areas.some(a=>!allowed.includes(a)))ctx.addIssue({code:"custom",path:["areas"],message:"One or more territories are invalid"});if(v.propertyTypes.some(p=>!PROPERTY_TYPES.includes(p)))ctx.addIssue({code:"custom",path:["propertyTypes"],message:"One or more property types are invalid"});}
export const realtorSchema=z.object({...realtorFields,termsAccepted:z.literal(true)}).superRefine(validateRealtorMarket);
export const realtorUpdateSchema=z.object(realtorFields).superRefine(validateRealtorMarket);
export const trackLeadSchema=z.object({leadId:z.string().regex(/^LEAD_[A-Za-z0-9]{8,40}$/i,"Invalid reference"),phone:z.string().min(7).max(30)});
